### ISSUE TITLE
Always show  Can't connect to MySQL server on 'mysql' (115)

### ISSUE THREAD

**Issue by gaankdoank** [psi-4ward/docker-powerdns#31]
Hi psitrax,

i've pulled this container and run on my host, but it always show  **Can't connect to MySQL server on 'mysql' (115)**, whereas i've configured mysql host.

Please help me, thanks,.

**Comment by psi-4ward** [comment]
Could you solve your problem?

**Comment by patrickscottbest** [comment]
This seems like a dead issue.  Perhaps @gaankdoank specified the MYSQL_HOST as "mysql" which either should have resolved for him, or not...  I guess we'll never know!

**Comment by pciavald** [comment]
Strangely i'm getting the same issue, i don't understand why. My docker-compose was giving this log and I tried the docker commands on the readme, same result.

My docker-compose:

```yml
version: '3'

services:

  pdns:
    image: psitrax/powerdns:latest
    container_name: pdns
    restart: always
    ports:
      - 53:53
      - 53:53/udp
    links:
      - pdns-db:mysql
    expose:
      - 8081
    environment:
      MYSQL_USER: root
      MYSQL_PASS: secret
      MYSQL_PORT: 3306

  pdns-db:
    image: mariadb:10.1
    container_name: pdns-db
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes: 
      - ./db:/var/lib/mysql

  admin:
    image: ngoduykhanh/powerdns-admin:latest
    container_name: pdns-admin
    restart: always
    ports:
      - 9191:80
    links:
      - pdns:pdns
    volumes:
      - admin-data:/data

volumes:
  admin-data:
```
